---
apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: ecommerce-namespace
type: Opaque
data:
  SA_PASSWORD:  MTgxOTk1QW0h # This is the base64 encoded value for '181995Am@'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  namespace: ecommerce-namespace
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql
        image: ammar2020/ecommerce-sql:latest
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 60
          periodSeconds: 
    

