apiVersion: v1
kind: Service
metadata:
  name: sql
  namespace: ecommerce-namespace
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
