apiVersion: v1
kind: Service
metadata:
  name: user-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
